# Generated by Django 3.0.5 on 2023-03-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(default='', max_length=15, verbose_name='otp')),
                ('user_id', models.IntegerField(unique=True, verbose_name='user_id')),
                ('start_otp', models.FloatField(default=0, verbose_name='start_otp')),
            ],
        ),
    ]
