# Generated by Django 3.0.5 on 2023-04-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_otp_start_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='serial',
            field=models.CharField(default='', max_length=10, unique=True, verbose_name='serial'),
        ),
    ]
